version: 0.2

phases:
  pre_build:
    commands:
      - echo Install dev dependencies
      - pip3 install -r requirements.txt
      - npm install -g aws-cdk

      - Docs test
      - apt-get update && apt-get install -y python3-pip
      - apt-get install make graphviz -y
      - make html
      
      - echo Lint with Black
      - black --check --diff app.py cdk_deployment

      - echo Lint with Flake
      - flake8 --count --max-line-length 88 app.py cdk_deployment
      
      - echo CDK Test
      - cdk synth


    
  build:
    commands:
      - echo Deploying Bootstrap Architecture...
      - cdk bootstrap -y --require-approval never
      - |
        if [[ -z "${LAMBDA_PIPELINE}" ]];then
          echo Deploying Pipeline Architecture...
          cdk deploy SDCAWSPipelineArchitectureStack -y --require-approval never
          echo Start other Codebuilds
          aws codebuild start-build --project-name build_sdc_aws_base_docker_image --region us-east-2
          aws codebuild start-build --project-name build_sdc_aws_sorting_lambda --region us-east-2
        else
          if [[ $LAMBDA_PIPELINE == *"SORTING"* ]];then
            echo Deploying Sorting Lambda
            cdk deploy SDCAWSSortingLambdaStack -y --require-approval never
          else
            echo Deploying Processing Lambda
            cdk deploy SDCAWSProcessingLambdaStack -y --require-approval never
          fi    
        fi   
   

      - echo Build completed on `date`
