# Terraform formatting
name: Terraform Formatting

on:
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      run: terraform fmt -check -recursive
