# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Building Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Graphviz and Make
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz make
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build docs
      run: make html
