# Terraform validation
name: Terraform Validation

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform validate (base)
      working-directory: base-infrastructure-terraform
      run: |
        terraform init -backend=false
        terraform validate
    - name: Terraform validate (pipeline)
      working-directory: pipeline-infrastructure-terraform
      run: |
        terraform init -backend=false
        terraform validate
